version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    env_file:
      - ./backend/.env.prod
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    volumes:
      - frontend_build:/frontend/build
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

  nginx:
    build: ./nginx
    ports:
      - "1337:80"
    volumes:
      # do i need this....???
      # also, do i need the "/default.conf:ro" part?
      # - ./nginx/nginx.conf:/etc/nginx/conf.d/
      - frontend_build:/var/www/frontend
      - static_volume:/app/backend/staticfiles
      - media_volume:/app/backend/mediafiles
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
  frontend_build:
  media_volume:
  static_volume:

