# Generated by Django 4.2.15 on 2024-09-17 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petimage',
            name='owner',
        ),
    ]
