# Generated by Django 4.2.15 on 2024-09-22 02:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pets.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pets', '0002_remove_petimage_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='description',
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_type',
            field=models.CharField(choices=[('cat', 'Cat'), ('dog', 'Dog'), ('fish', 'Fish'), ('reptile', 'Reptile'), ('bird', 'Bird'), ('plant', 'Plant'), ('other', 'Other')], max_length=15),
        ),
        migrations.CreateModel(
            name='PetPic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pet_type', models.CharField(choices=[('cat', 'Cat'), ('dog', 'Dog'), ('fish', 'Fish'), ('reptile', 'Reptile'), ('bird', 'Bird'), ('plant', 'Plant'), ('other', 'Other')], max_length=15)),
                ('name', models.CharField(max_length=100)),
                ('breed', models.CharField(blank=True, max_length=100, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(upload_to=pets.models.get_file_path_image)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
