# Generated by Django 4.2.15 on 2024-09-22 05:36

from django.db import migrations, models
import pets.models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_remove_pet_description_alter_pet_pet_type_petpic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petpic',
            name='image',
            field=models.ImageField(upload_to=pets.models.get_file_path_pic),
        ),
    ]
